# -*- coding: utf-8 -*-
"""
/***************************************************************************
 forestFireViewer
                                 A QGIS plugin
 Forest Fire Viewer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-07
        copyright            : (C) 2025 by Jaan Soulier
        email                : jaansoulier@cmail.carleton.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load forestFireViewer class from file forestFireViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .forestFireViewer import forestFireViewer
    return forestFireViewer(iface)
